# Generated by Django 3.1.5 on 2021-10-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=120)),
                ('about', models.TextField()),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
